### ISSUE TITLE
[BUG] 程序未能识别含大写 UUID 字符串的 Vless 分享链接

### ISSUE THREAD

**Issue by ssrkaze** [asdlokj1qpi233/subconverter#11]
### 确认版本最新

- [ ] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [x] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.9.8-bc7e2c2 backend

### 转换过程

Vless 分享链接转为 Clash 节点

### 转换设置

忽略其他配置项目。
无法正确转换的写法：
```yaml
common:
  # 额外添加的节点
  insert_url:
    - vless://EFBE3B3D-124D-4F61-AFDC-525421246B9B@127.0.0.1:32028?encryption=none&security=reality&type=tcp&sni=itunes.apple.com&fp=chrome&pbk=At3g9qD-pAANQCtWgNLIjQbw8h50_cWl9S0bjhEUXXA&sid=6ba85179e30d4fc2&flow=xtls-rprx-vision#efbe3b3d-VLESS_Reality_Vision
```
能正确转换的写法
```yaml
common:
  # 额外添加的节点
  insert_url:
    - vless://efbe3b3d-124d-4f61-afdc-525421246b9b@127.0.0.1:32028?encryption=none&security=reality&type=tcp&sni=itunes.apple.com&fp=chrome&pbk=At3g9qD-pAANQCtWgNLIjQbw8h50_cWl9S0bjhEUXXA&sid=6ba85179e30d4fc2&flow=xtls-rprx-vision#efbe3b3d-VLESS_Reality_Vision
```

### 复现步骤

在将 Vless 分享链接插入 common -> insert_url 中作为额外插入的节点。
使用大写的 UUID ，将无法生成 Clash 配置文件。
而将 UUID 转换为小写之后，能正确生成相应的节点信息。

### 期望结果

忽略其他配置
```yaml
proxies:
  - {name: efbe3b3d-VLESS_Reality_Vision, server: 127.0.0.1, port: 32028, type: vless, uuid: EFBE3B3D-124D-4F61-AFDC-525421246B9B, tls: true, flow: xtls-rprx-vision, reality-opts: {public-key: At3g9qD-pAANQCtWgNLIjQbw8h50_cWl9S0bjhEUXXA, short-id: "6ba85179e30d4fc2" }, servername: itunes.apple.com, client-fingerprint: chrome, network: tcp}
```

### 实际结果

页面回显
```
The following link doesn't contain any valid node info: vless://EFBE3B3D-124D-4F61-AFDC-525421246B9B@127.0.0.1:32028?encryption=none&security=reality&type=tcp&sni=itunes.apple.com&fp=chrome&pbk=At3g9qD-pAANQCtWgNLIjQbw8h50_cWl9S0bjhEUXXA&sid=6ba85179e30d4fc2&flow=xtls-rprx-vision#efbe3b3d-VLESS_Reality_Vision
```

### 错误信息

```shell
2025/01/22 Wed 13:27:18.294856 [1 Thread-3][INFO] Fetching node data from url 'vless://EFBE3B3D-124D-4F61-AFDC-525421246B9B@127.0.0.1:32028?encryption=none&security=reality&type=tcp&sni=itunes.apple.com&fp=chrome&pbk=At3g9qD-pAANQCtWgNLIjQbw8h50_cWl9S0bjhEUXXA&sid=6ba85179e30d4fc2&flow=xtls-rprx-vision#efbe3b3d-VLESS_Reality_Vision'.
2025/01/22 Wed 13:27:18.294901 [1 Thread-3][VERB] Received Link.
2025/01/22 Wed 13:27:18.295157 [1 Thread-3][VERB] No valid link found.
```
