### ISSUE TITLE
[Feature] Can add QUIC parametersthe and port hopping function for converting Hysteria2 、Hysteria?

### ISSUE THREAD

**Issue by zxlhhyccc** [asdlokj1qpi233/subconverter#2]
### verify

- [X] 我已经仔细阅读[项目文档](https://github.com/tindy2013/subconverter/blob/master/README-cn.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/tindy2013/subconverter/issues)，确认与现有issue的内容并不重复
- [X] 我已经尝试自行解决，确认自己没有能力解决

### 功能描述

Can add QUIC parametersthe and port hopping function for converting Hysteria2 、Hysteria?

**Comment by asdlokj1qpi233** [comment]
If you are using Meta Clash (Mihomo).
```yaml
- name: xxx
  type: hysteria2
  port: 2088
  ports: 2088-3999
  server: xxx
  sni: xxx
  password: xxx
  auth: xxx
```
The ports parameter will be useful.
