### ISSUE TITLE
[BUG] vless 节点 v2ray-http-upgrade 选项转换后丢失

### ISSUE THREAD

**Issue by Glavor** [asdlokj1qpi233/subconverter#31]
### 确认版本最新

- [x] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [x] 我已经确认之前没有issue涉及此BUG

### subconverter版本

subconverter v0.9.9-4ae0d1b

### 转换过程

clash 转为 clash

### 转换设置

默认

### 复现步骤

转换如下包含 v2ray-http-upgrade 选项的 vless 节点
```yaml
proxies:
  - name: test
    type: vless
    server: test.test.com
    port: 443
    uuid: c9c1e808-5244-4271-bf22-2560bd8a832e
    udp: true
    tls: true
    network: ws
    ws-opts:
      path: /test
      headers:
        Host: test.test.com
      v2ray-http-upgrade: true
```

### 期望结果

v2ray-http-upgrade 选项保留

### 实际结果

转换后 v2ray-http-upgrade 选项丢失
```yaml
proxies:
  - {name: test, server: test.test.com, port: 443, type: vless, uuid: c9c1e808-5244-4271-bf22-2560bd8a832e, tls: true, network: ws, ws-opts: {path: /test, headers: {Host: test.test.com}}, udp: true}
```

### 错误信息

```shell
无
```
