### ISSUE TITLE
[BUG] Clash Vless配置转换为V2ray配置时丢失reality信息

### ISSUE THREAD

**Issue by Chandler-Lu** [asdlokj1qpi233/subconverter#37]
### 确认版本最新

- [x] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [x] 我已经确认之前没有issue涉及此BUG

### subconverter版本

383deb5

### 转换过程

Clash Vless配置转换为V2ray

### 转换设置

默认配置文件，target=mixed&url=AAAA

### 复现步骤

使用了如下 Clash 配置，通过 Subconverter 转换为 Mixed 配置，解析出 `vless://XXX@XXX:XXX?&security=tls&.....`的地址，在 V2rayN 导入后 security 被设置为 tls，配置错误
```
  - name: "XX"
    type: vless
    server: XXX
    port: XXX
    uuid: XXX
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: XXX
    reality-opts:
      public-key: XXX
      short-id: XXX
    client-fingerprint: chrome
```

### 期望结果

应当解析为 `security=reality`

### 实际结果

`security=tls`

### 错误信息

```shell

```
