### ISSUE TITLE
[BUG] IPv6 地址 `server` 处理不适配 mihomo 和 sing-boxp 内核

### ISSUE THREAD

**Issue by DustinWin** [asdlokj1qpi233/subconverter#39]
### 确认版本最新

- [x] 我已经确认在最新Action编译的版本中复现

### 检索issue

- [x] 我已经确认之前没有issue涉及此BUG

### subconverter版本

v0.9.8

### 转换过程

Trojan 转 Clash

### 转换设置

https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_MultiMode.ini

### 复现步骤

[cmliu/epeius](https://github.com/cmliu/epeius) 项目（项目作者叫我来找您）中，在 <https://{yourdomain}/{uuid}/edit> 里填入优选 IPv6 地址如：`[2606:4700:3036:0:a36a:4af2:65e7:a0d6]#CMCC-IPv6节点` 时，将生成的 clash 订阅 <https://{yourdomain}/{uuid}?clash> 导入到 [mihomo](https://github.com/MetaCubeX/mihomo) 内核（v1.19.10）中使用，IPv6 地址的中括号 `[]` 会一并带入到 `proxies.server` 配置项中，从而导致节点无效，如：
```yaml
proxies:
  - name: "CMCC-IPv6节点"
    server: "[2606:4700:3036:0:a36a:4af2:65e7:a0d6]"
    port: 443
    type: trojan
    password: uuid
    sni: example.com
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: "/?ed=2560"
      headers:
        Host: example.com
```
必须去掉 `proxies.server` 里的中括号 `[]`，该节点才有效
mihomo 内核那边的解释是：`server` 参数的值是服务器，不是 url 链接，所以不能加中括号

包括 [sing-boxp](https://github.com/PuerNya/sing-box/tree/building) 内核（支持 `outbound_providers` 订阅的第三方 sing-box 内核）也是如此：
```json
{
  "outbounds": [
    {
      "type": "trojan",
      "tag": "CMCC-IPv6节点",
      "server": "[2606:4700:3036:0:a36a:4af2:65e7:a0d6]",
      "server_port": 443,
      "password": "uuid",
      "transport": {
        "type": "ws",
        "path": "/?ed=2560",
        "headers": {
          "Host": "example.com"
        }
      },
      "tls": {
        "enabled": true,
        "server_name": "example.com",
        "insecure": true
      },
      "tcp_fast_open": false
    }
  ]
}
```
必须去掉 `outbounds.server` 里的中括号 `[]`，该节点才有效

### 期望结果

`server` 中的 IPv6 地址没有中括号

### 实际结果

`server` 中的 IPv6 地址有中括号

### 错误信息

```shell

```
